### ISSUE TITLE
Unable to download capsule_data.tar.gz .

### ISSUE THREAD

**Issue by GajulapalliNagaVyshnavi** [maranasgroup/CatPred#10]
Can someone help me to download  the capsule_data file as i am getting below error when i am tryinig to download.
![image](https://github.com/user-attachments/assets/199978e2-a34a-4e95-a027-e82de7bba16f)

**Comment by Vedasheersh** [comment]
Hello @GajulapalliNagaVyshnavi ,

Thank you for your interest in our work. It looks like the previous download links were broken because of some updates to the repository. Please try now, the issue should be fixed. 

Feel free to open an issue in case of any other problems. 

Veda.
