### ISSUE TITLE
hope a readme

### ISSUE THREAD

**Issue by liangzais** [maranasgroup/CatPred#6]
Could you please make the training process public?

**Comment by Vedasheersh** [comment]
Hi @liangzais,

Thank you for your interest. It will be made public as soon as the article is published.

Veda.

**Comment by Vedasheersh** [comment]
The repository has now been updated with some scripts to reproduce results of the manuscript. These can be easily modified to suit any training needs. 

Please feel free to open an issue in case of any problems,

Veda.
