### ISSUE TITLE
CatPred shows "Prediction failed"

### ISSUE THREAD

**Issue by msandy1013** [maranasgroup/CatPred#9]
After running the cell, it is showing "Prediction failed". However, few days back, this was still giving desired results only. Can you please let me know the probable reason for showing such an error?

Note that I run with just default cells.

![image](https://github.com/user-attachments/assets/01844114-0bef-4eac-b027-5af1dac54f76)

**Comment by Vedasheersh** [comment]
Hello @msandy1013 ,

Thank you for the interest in our work. The Colab notebook codes are now updated to reflect some of the recent changes we made to the Github repo. The code should now work without any issue. Please do check again.

Best,
Veda.

**Comment by msandy1013** [comment]
Hello Veda,
Thank you so much. Now it's working.
